#!/bin/bash
# Quick test script for UF2 bootloader

echo "================================================"
echo "  HPM UF2 Bootloader Quick Test"
echo "================================================"
echo ""
echo "Binary location: build/output/hpm-uf2-boot.{elf,bin}"
echo ""
echo "To flash:"
echo "  openocd -f your_config.cfg \\"
echo "    -c 'program build/output/hpm-uf2-boot.elf 0x80000000 verify reset exit'"
echo ""
echo "To monitor serial (115200 baud):"
echo "  picocom -b 115200 /dev/ttyUSB0"
echo ""
echo "To check USB:"
echo "  lsusb"
echo "  sudo dmesg | tail"
echo ""
echo "================================================"
